.TH "clientGlobalStruct" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clientGlobalStruct \- 
.SH SYNOPSIS
.br
.PP
\fC#include <w3client.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "w3Thread ** \fBthreads\fP"
.br
.ti -1c
.RI "int \fBnumOfThreads\fP"
.br
.ti -1c
.RI "char * \fBhostname\fP"
.br
.ti -1c
.RI "char * \fBlastpath\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* \fBclientGlobalStruct::hostname\fP"
.PP
.SS "char* \fBclientGlobalStruct::lastpath\fP"
.PP
.SS "int \fBclientGlobalStruct::numOfThreads\fP"
.PP
.SS "int \fBclientGlobalStruct::port\fP"
.PP
.SS "w3Thread** \fBclientGlobalStruct::threads\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
