.TH "config.h" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBHAVE_LIBNSL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LIBPTHREAD\fP   1"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define HAVE_LIBNSL   1"
.PP
.SS "#define HAVE_LIBPTHREAD   1"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
