.TH "MTDocStruct" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MTDocStruct \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBuriString\fP"
.br
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* \fBMTDocStruct::filename\fP"
.PP
.SS "int \fBMTDocStruct::port\fP"
.PP
.SS "char* \fBMTDocStruct::uriString\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
