.TH "myStruct" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myStruct \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBtext\fP [10]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char \fBmyStruct::text\fP[10]"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
