.TH "main.c" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <w3thread.h>\fP
.br
\fC#include <w3server.h>\fP
.br
\fC#include <string.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBmyStruct\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBdummyFunction\fP (void *ptr)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* dummyFunction (void * ptr)"
.PP
.SS "int main (int argc, char * argv[])"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
