.TH "w3clientconfig.h" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
w3clientconfig.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'config.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBW3_CLIENT_CACHE_DIR_DEF\fP   'cache/'"
.br
.ti -1c
.RI "#define \fBW3_CLIENT_INDEX_HTML_DEF\fP   '/index.html'"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define W3_CLIENT_CACHE_DIR_DEF   'cache/'"
.PP
.SS "#define W3_CLIENT_INDEX_HTML_DEF   '/index.html'"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
