.TH "w3error.c" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
w3error.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <w3error.h>\fP
.br
\fC#include <stdio.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBw3Error\fP (const char *message)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
