.TH "w3error.h" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
w3error.h \- Error output functions. 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBw3Error\fP (const char *message)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Error output functions. 


.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
