.TH "w3html.h" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
w3html.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <w3types.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBW3_HTML_400\fP   1"
.br
.ti -1c
.RI "#define \fBW3_HTML_404\fP   2"
.br
.ti -1c
.RI "#define \fBW3_HTML_503\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBw3HTMLGenerateError\fP (char *header, char *info, int pagecode)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define W3_HTML_400   1"
.PP
.SS "#define W3_HTML_404   2"
.PP
.SS "#define W3_HTML_503   3"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
