.TH "w3ServerConnection" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
w3ServerConnection \- 
.SH SYNOPSIS
.br
.PP
\fC#include <w3server.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBw3Server\fP * \fBserver\fP"
.br
.ti -1c
.RI "sockaddr_in \fBsock_addr\fP"
.br
.ti -1c
.RI "socklen_t \fBaddrlen\fP"
.br
.ti -1c
.RI "int \fBsocket\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "socklen_t \fBw3ServerConnection::addrlen\fP"
.PP
.SS "\fBw3Server\fP* \fBw3ServerConnection::server\fP"
.PP
.SS "struct sockaddr_in \fBw3ServerConnection::sock_addr\fP"
.PP
.SS "int \fBw3ServerConnection::socket\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
