.TH "w3Server" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
w3Server \- 
.SH SYNOPSIS
.br
.PP
\fC#include <w3server.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsocket\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "char * \fBhostname\fP"
.br
.ti -1c
.RI "sockaddr_in \fBsock_addr\fP"
.br
.ti -1c
.RI "hostent * \fBhost\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct hostent* \fBw3Server::host\fP"
.PP
.SS "char* \fBw3Server::hostname\fP"
.PP
.SS "int \fBw3Server::port\fP"
.PP
.SS "struct sockaddr_in \fBw3Server::sock_addr\fP"
.PP
.SS "int \fBw3Server::socket\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
