.TH "w3string.c" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
w3string.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <w3string.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBcomposeString\fP (char *str1, char *str2)"
.br
.ti -1c
.RI "char * \fBcopyString\fP (char *str)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
