.TH "w3string.h" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
w3string.h \- Convenience functions to handle \fCchar*\fP strings. 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBcomposeString\fP (char *str1, char *str2)"
.br
.ti -1c
.RI "char * \fBcopyString\fP (char *str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Convenience functions to handle \fCchar*\fP strings. 


.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
