.TH "w3types.h" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
w3types.h \- Type definitions. 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <netinet/in.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBw3URI\fP"
.br
.ti -1c
.RI "struct \fBw3ClientConnection\fP"
.br
.ti -1c
.RI "struct \fBw3Document\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBtrue\fP   1"
.br
.ti -1c
.RI "#define \fBfalse\fP   0"
.br
.ti -1c
.RI "#define \fBCR\fP   13"
.br
.ti -1c
.RI "#define \fBLF\fP   10"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBboolean\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type definitions. 

\fBAuthor:\fP
.RS 4
Christian Gosch 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
