.TH "w3uri.h" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
w3uri.h \- Functions to manipulate URIs. 
.SH SYNOPSIS
.br
.PP
\fC#include <w3types.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBboolean\fP \fBw3ParseURI\fP (const char *uristr, \fBw3URI\fP *uri)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions to manipulate URIs. 


.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
