.TH "w3uri.c" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
w3uri.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <w3uri.h>\fP
.br
\fC#include <w3string.h>\fP
.br
\fC#include <w3clientconfig.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBw3ParseURIGetToken\fP (char *str, int *i, char lastChar)"
.br
.ti -1c
.RI "\fBboolean\fP \fBw3ParseURI\fP (const char *uriString, \fBw3URI\fP *uri)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* w3ParseURIGetToken (char * str, int * i, char lastChar)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
