.TH "yy_buffer_state" 3 "6 Jul 2006" "Version 1.0" "w3server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yy_buffer_state \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "FILE * \fByy_input_file\fP"
.br
.ti -1c
.RI "char * \fByy_ch_buf\fP"
.br
.ti -1c
.RI "char * \fByy_buf_pos\fP"
.br
.ti -1c
.RI "\fByy_size_t\fP \fByy_buf_size\fP"
.br
.ti -1c
.RI "int \fByy_n_chars\fP"
.br
.ti -1c
.RI "int \fByy_is_our_buffer\fP"
.br
.ti -1c
.RI "int \fByy_is_interactive\fP"
.br
.ti -1c
.RI "int \fByy_at_bol\fP"
.br
.ti -1c
.RI "int \fByy_fill_buffer\fP"
.br
.ti -1c
.RI "int \fByy_buffer_status\fP"
.br
.ti -1c
.RI "FILE * \fByy_input_file\fP"
.br
.ti -1c
.RI "char * \fByy_ch_buf\fP"
.br
.ti -1c
.RI "char * \fByy_buf_pos\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fByy_buffer_state::yy_at_bol\fP"
.PP
.SS "char* \fByy_buffer_state::yy_buf_pos\fP"
.PP
.SS "char* \fByy_buffer_state::yy_buf_pos\fP"
.PP
.SS "\fByy_size_t\fP \fByy_buffer_state::yy_buf_size\fP"
.PP
.SS "int \fByy_buffer_state::yy_buffer_status\fP"
.PP
.SS "char* \fByy_buffer_state::yy_ch_buf\fP"
.PP
.SS "char* \fByy_buffer_state::yy_ch_buf\fP"
.PP
.SS "int \fByy_buffer_state::yy_fill_buffer\fP"
.PP
.SS "FILE* \fByy_buffer_state::yy_input_file\fP"
.PP
.SS "FILE* \fByy_buffer_state::yy_input_file\fP"
.PP
.SS "int \fByy_buffer_state::yy_is_interactive\fP"
.PP
.SS "int \fByy_buffer_state::yy_is_our_buffer\fP"
.PP
.SS "int \fByy_buffer_state::yy_n_chars\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for w3server from the source code.
